name: u01
favicon: null
layout_spectrum: 0.7895518464501947
typography_spectrum: 0.3118686964735389
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.153826066525653
  lightness: 0.4222756982780993
  saturation: 0.8248070669360459
  rhythmicContrast: 0.21525081433355808
purpose: []
